<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>7.3</LangVersion>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <RimworldModDirectory>/media/Games/SteamLibrary/steamapps/common/RimWorld/Mods/</RimworldModDirectory>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DebugSymbols>false</DebugSymbols>
      <OutputPath>../Mod/1.6/Assemblies</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <OutputPath>../Mod/1.6/Assemblies</OutputPath>
      <DebugType>none</DebugType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Lib.Harmony" Version="2.4.2" />
      <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\..\..\..\..\..\..\SteamLibrary\steamapps\common\RimWorld\RimWorldLinux_Data\Managed\Assembly-CSharp.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>..\..\..\..\..\..\..\SteamLibrary\steamapps\common\RimWorld\RimWorldLinux_Data\Managed\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\..\..\..\..\..\..\SteamLibrary\steamapps\common\RimWorld\RimWorldLinux_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="VREAndroids">
        <HintPath>..\..\..\..\..\..\..\SteamLibrary\steamapps\workshop\content\294100\2975771801\1.6\Assemblies\VREAndroids.dll</HintPath>
        <Private>False</Private>
      </Reference>
    </ItemGroup>

    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
      <Exec Command="rm -rf $(TargetDir)" />
    </Target>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="rm -rf $(RimworldModDirectory)$(TargetName)/; &#xA;mkdir $(RimworldModDirectory)$(TargetName)/; &#xA;cp -rf $(ProjectDir)../Mod/*  $(RimworldModDirectory)$(TargetName)/" />
    </Target>

</Project>
